enum ApiStatus {
  SUCCESS = "SUCCESS",
  ERROR = "ERROR",
  FAIL = "FAIL",
  NOT_FOUND = "NOT_FOUND",
  AUTHORIZATION_ERROR = "AUTHORIZATION_ERROR",
  AUTHENTICATION_ERROR = "AUTHENTICATION_ERROR",
}

export default ApiStatus;
